= RateLimit Policy


ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-ratelimit/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-ratelimit/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

|===
|onRequest |onResponse

| X
|

|===

== Description

There are three rate limit policies:

* Quota: configure the number of requests allowed over a period of time (Hours, Days, Weeks, Months)
* Rate-Limit: configure the number of requests allowed over a limited period of time ( Seconds, Minutes)
* Spike-Arrest: throttle the number of requests processed and send to the backend to avoid spike

== Configuration

You can configure the policy with the following options :

=== Quota

Quota Policy configures the number of requests allow over an important period of time (from Hour to Month).
This policy doesn't prevent from spike of request.

|===
|Property |Required |Description |Type |Default

|key
|No
|Key to identify a consumer against whom the quota will be applied. Leave it empty to use the default behavior (plan/subscription pair). Supports EL.
|String
|null

|limit
|No
|Static limit on the number of requests that can be sent (this limit is used if the value > 0).
|integer
|0

|dynamicLimit
|No
|Dynamic limit on the number of requests that can be sent (this limit is used if static limit = 0). The dynamic value is based on EL expressions.
|string
|null

|periodTime
|Yes
|Time duration
|Integer
|1

|periodTimeUnit
|Yes
|Time unit ("HOURS", "DAYS", "WEEKS", "MONTHS")
|String
|MONTHS

|===


[source, json]
.Sample
----
  "quota": {
    "limit": "1000",
    "periodTime": 1,
    "periodTimeUnit": "MONTHS"
  }
----

=== Rate-Limit

Rate-Limit Policy configures the number of requests allow over a limited period of time (from Seconds to Minutes).
This policy doesn't prevent from spike of request.

|===
|Property |Required |Description |Type |Default

|key
|No
|Key to identify a consumer against whom the rate-limiting will be applied. Leave it empty to use the default behavior (plan/subscription pair). Supports EL.
|String
|null

|limit
|No
|Static limit on the number of requests that can be sent (this limit is used if the value > 0).
|integer
|0

|dynamicLimit
|No
|Dynamic limit on the number of requests that can be sent (this limit is used if static limit = 0). The dynamic value is based on EL expressions.
|string
|null

|periodTime
|Yes
|Time duration
|Integer
|1

|periodTimeUnit
|Yes
|Time unit ("SECONDS", "MINUTES" )
|String
|SECONDS

|===


[source, json]
.Sample
----
  "rate": {
    "limit": "10",
    "periodTime": 10,
    "periodTimeUnit": "MINUTES"
  }
----

=== Spike Arrest

Spike-Arrest Policy configures the number of requests allow over a limited period of time (from Seconds to Minutes).
This policy prevents from spike of request by throttling incoming requests.
For example, a SpikeArrest policy configured to 2000request/second will limit the execution of simultaneous requests to 200 requests per 100ms.

By default, SpikeArrest policy is applied on a plan not on a consumer. To apply a spike arrest per consumer, please use the 'key' attribute which supports https://docs.gravitee.io/apim/3.x/apim_publisherguide_expression_language.html[Expression Language].

|===
|Property |Required |Description |Type |Default

|key
|No
|Key to identify a consumer against whom the spike limit will be applied. Leave it empty to use the default behavior. Supports EL (example: `{#request.headers['x-consumer-id']}`)
|String
|null

|limit
|No
|Static limit on the number of requests that can be sent (this limit is used if the value > 0).
|integer
|0

|dynamicLimit
|No
|Dynamic limit on the number of requests that can be sent (this limit is used if static limit = 0). The dynamic value is based on EL expressions.
|string
|null

|periodTime
|Yes
|Time duration
|Integer
|1

|periodTimeUnit
|Yes
|Time unit ("SECONDS", "MINUTES" )
|String
|SECONDS

|===


[source, json]
.Sample
----
  "spike": {
    "limit": "10",
    "periodTime": 10,
    "periodTimeUnit": "MINUTES"
  }
----

== Errors
If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys send by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|RATE_LIMIT_TOO_MANY_REQUESTS
^.^|limit - period_time - period_unit

.^|QUOTA_TOO_MANY_REQUESTS
^.^|limit - period_time - period_unit

.^|SPIKE_ARREST_TOO_MANY_REQUESTS
^.^|limit - period_time - period_unit - slice_limit - slice_period_time - slice_limit_period_unit

|===
